using System.Collections.Generic;
using Project.Core.Core.Grid;
using Project.Gameplay.Gameplay.Combat.Effects;
using Project.Gameplay.Gameplay.Figures;
using Project.Gameplay.Gameplay.Grid;

namespace Project.Gameplay.Gameplay.Combat.Contexts
{
    public sealed class AfterHitContext : ICombatEffectSink
    {
        public Figure Attacker { get; set; }
        public Figure Target { get; set; }
        public GridPosition AttackerPosition { get; set; }
        public GridPosition TargetPosition { get; set; }
        public BoardGrid Grid { get; set; }
        
        public int DamageDealt { get; set; }
        public bool TargetDied { get; set; }
        public bool WasCritical { get; set; }
        
        /// <summary>
        /// Combat effects generated by passives.
        /// </summary>
        public List<ICombatEffect> Effects { get; } = new();
        
        public void AddEffect(ICombatEffect effect) => Effects.Add(effect);
    }
}
